select * from runners;
--insert into runners(runner_id, device_id, nom, cognoms, parella_id)	values (default, 101, 'nom', 'congoms', 100);
delete from runners_controls;
delete from points;
delete from runners;


insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,657, 'Martí', 'Gorchs Picas', 656);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,656, 'Aniol', 'Ramon Oller', 657);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,658, 'Isma', 'Martinez Delgado', 659);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,659, 'Renaud', 'Alexandron', 658);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,646, 'Bernat', 'Perez Costa', 647);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,647, 'Jordi', 'Perarnau Guillemas', 646);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,637, 'Ricard', 'Bajona', 636);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,636, 'Albert', 'Astor Sellares', 637);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,690, 'Raimon', 'Vallverdú Colom', 692);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,692, 'Roger', 'Villena Ferrer', 690);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,683, 'Montserrat', 'Gudayol Portabella', 681);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,681, 'Sergi', 'Reixach Reyes', 683);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,729, 'Quicu', 'Tàpias Anton', 652);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,652, 'Marc', 'Pirla Casasayas', 729);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,668, 'Albert', 'Contreras Busquets', 667);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,667, 'Montserrat', 'Barrera Sanchez', 668);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,616, 'Júlia', 'Martinez Cervelló', 615);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,615, 'Mariona', 'Jordan Clariana', 616);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,634, 'David', 'Serra Ferrer', 635);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,635, 'Marc', 'Puig Tabueña', 634);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,716, 'Albert', 'Bellés Muñoz', 725);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,725, 'Roger', 'Llonch', 716);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,660, 'Pol', 'Garriga Martín', 661);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,661, 'Helena', 'Estapé Grau', 660);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,724, 'David', 'Jorba Ladron de Guevara', 644);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,644, 'Enric', 'Franco Peris', 724);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,618, 'Neus', 'Cervera Pallejà', 619);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,619, 'Evelyne', 'Duch Castella', 618);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,730, 'Toni', 'Elias Oriol', 643);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,643, 'Jaume', 'Capdevila Elcacho', 730);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,700, 'Carla', 'Vigo', 727);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,727, 'Aleix', 'Belliure', 700);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,665, 'Jordi', 'Maeso Nuet', 666);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,666, 'Berta', 'Maeso Deitg', 665);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,693, 'Gil', 'Perarnau Prat', 691);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,691, 'Oriol', 'Guix Font', 693);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,628, 'Oriol', 'Granés', 629);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,629, 'Àlex', 'Dalmases Llordes', 628);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,648, 'Jordi', 'Montero Lujan', 649);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,649, 'Martí', 'Sancho Masip', 648);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,731, 'Sergi', 'Camí Martínez', 640);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,640, 'Josep', 'Paretas Rosas', 731);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,662, 'Iris', 'López Poch', 664);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,664, 'Roger', 'Alcántara Climent', 662);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,654, 'David', 'Ramon Rubinat', 655);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,655, 'Carmelo', 'Ramon Prat', 654);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,670, 'Raxaa', 'Khlifi Alami', 669);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,669, 'Marçal', 'Roca', 670);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,627, 'Oriol', 'Comas', 626);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,626, 'Pere', 'Urgellés', 627);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,633, 'Nacho', 'Alonso Barbé', 631);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,631, 'Oriol', 'Guim Marzo', 633);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,687, 'Jose', 'Codoñer Plaza', 684);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,684, 'Núria', 'Cardús Marcos', 687);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,698, 'Paco', 'Navarro Salmerón', 699);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,699, 'Marcos', 'Magdalena Vázquez', 698);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,674, 'Marc', 'Cartanyà Farré', 673);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,673, 'Alba', 'Saura Capdevila', 674);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,696, 'Joan', 'Baltà Torredemer', 695);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,695, 'Joan', 'Baltà Rosaura', 696);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,671, 'Berta', 'Riera Bayer', 672);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,672, 'Joan', 'Oliva Segú', 671);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,678, 'Pili', 'Guiral Trejos', 677);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,677, 'Edgart', 'Gonzàlez Arboix', 678);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,650, 'Alex', 'Viver Puig', 651);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,651, 'Antoni', 'Feliu Bermúdez', 650);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,688, 'Jan', 'Ballbè Perés', 689);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,689, 'Elisabet', 'Perés Font', 688);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,728, 'Albert', 'Borrull Preixens', 639);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,639, 'Toni', 'Verdú Mateo', 728);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,622, 'Neus', 'Ordeix Elias', 621);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,621, 'Mercè', 'Ordeix Elias', 622);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,623, 'Meritxell', 'Martí Gómez', 624);
insert into runners(runner_id, device_id, nom, cognoms, parella_id) values (default,624, 'Judit', 'Bartoli', 623);